title: Mathai Sibu Kombasseril # your name (or website title) here
logo: "/images/Github_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist | Machine Learning, Risk & GenAI 
  <br><br>
  Data Science @ <a href="https://www.aroundzero.net/" target="_blank">Around Zero Ltd</a>
  <br><br>
  "Building production-grade ML, forecasting, and Generative AI solutions that solve real business problems. Experienced across financial services, retail, and the public sector, delivering measurable impact through fraud detection, credit risk modelling, forecasting, document intelligence, and enterprise automation."
  <br><br>
  <a href="https://www.linkedin.com/in/mathai-k-sibu/" target="_blank">View my LinkedIn Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colours:
  crimson: '#900C3F'
